packages:
  - apps/*
  - packages/*
  - packages/shared/*
onlyBuiltDependencies:
  - better-sqlite3
  - bufferutil
  - ccxt
  - esbuild
  - sqlite3
  - utf-8-validate
ignoredBuiltDependencies:
  - bigint-buffer
  - unrs-resolver
